name: Deploy to GitHub Pages

on:
  # 推送到 main 分支时触发
  push:
    branches: [ main ]
  
  # 手动触发
  workflow_dispatch:

# 设置 GITHUB_TOKEN 权限
permissions:
  contents: read
  pages: write
  id-token: write

# 确保只有一个部署作业同时运行
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 构建和部署作业
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: 配置 Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: 确保 .nojekyll 文件存在
        run: |
          touch .nojekyll
          echo "已创建 .nojekyll 文件以禁用 Jekyll 处理"
          
      - name: 设置 Pages
        uses: actions/configure-pages@v4
        
      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
